### ISSUE TITLE
BUG | 箭头格式为矩形线时运行脚本，线条样式会乱码 

### ISSUE THREAD

**Issue by LeCheenaX** [pandoralink/obsidian-excalidraw-plugin-scripts#1]
## 描述：
当使用矩形线(elbow arrow)时，
![image](https://github.com/user-attachments/assets/27c49551-67a4-494e-ab1c-5f300bdcc9c8)
运行脚本，发现有多个子块的矩形连线会挤成一团：
![image](https://github.com/user-attachments/assets/6a613185-f65b-4798-8652-bd30d56f8871)

此问题在其他连线样式中未复现。

## 临时解决方案：
手动双击出问题的块，才会恢复。或者移动它们的母块。

## 期待解决方案：
矩形连线格式可以稳定一点，比如自动刷新箭头始终点位置。

**Comment by pandoralink** [comment]
竟然被你发现这个库了，发个测试文件，我今晚帮你看看，修复下

**Comment by LeCheenaX** [comment]
> 竟然被你发现这个库了，发个测试文件，我今晚帮你看看，修复下

感谢回复！抱歉回晚了。底下附件我刚刚测试了，全选方框之后，运行脚本就会复现问题。

运行前：
![image](https://github.com/user-attachments/assets/dee22132-f7bf-49be-8adf-9e8abfeb83c8)
运行后：
![image](https://github.com/user-attachments/assets/0f93d80f-d607-4c88-b41e-83aa25244032)
---
测试文件：
[Drawing 2024-09-02 21.08.25.excalidraw.md](https://github.com/user-attachments/files/18222320/Drawing.2024-09-02.21.08.25.excalidraw.md)

再次感谢你关注这个问题！

**Comment by pandoralink** [comment]
> > 竟然被你发现这个库了，发个测试文件，我今晚帮你看看，修复下
> 
> 感谢回复！抱歉回晚了。底下附件我刚刚测试了，全选方框之后，运行脚本就会复现问题。
> 
> ## 运行前：
> ![image](https://private-user-images.githubusercontent.com/102142515/397994203-dee22132-f7bf-49be-8adf-9e8abfeb83c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTI1NTUsIm5iZiI6MTczNTA1MjI1NSwicGF0aCI6Ii8xMDIxNDI1MTUvMzk3OTk0MjAzLWRlZTIyMTMyLWY3YmYtNDliZS04YWRmLTllOGFiZmViODNjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNDU3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJhMDI1YTVkMWZiOTkzMjdkZDM1MjMwY2U2MDRlM2U2YWNjYmI5MjMyYzlkYTA5NWE0YjE0ODk2YWQwOGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NNRXwwlfKS2nibU597-DLPPZiiz4Cn105Yr1W5qq5ck)
> 运行后：
> ![image](https://private-user-images.githubusercontent.com/102142515/397994236-0f93d80f-d607-4c88-b41e-83aa25244032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTI1NTUsIm5iZiI6MTczNTA1MjI1NSwicGF0aCI6Ii8xMDIxNDI1MTUvMzk3OTk0MjM2LTBmOTNkODBmLWQ2MDctNGM4OC1iNDFlLTgzYWEyNTI0NDAzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNDU3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzNlYjVhYzAzOWNmMDRkMjMyZjlmZDA1MTFmNzFiMDc2NTMyNWE3MTA5NDBlZjcyZGJjYjAyMDAyOWQwMWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ONNXgk-TQS8KIgvfQQQPfF114Po5b8RMpJyiAEbCGGY)
> 测试文件： [Drawing 2024-09-02 21.08.25.excalidraw.md](https://github.com/user-attachments/files/18222320/Drawing.2024-09-02.21.08.25.excalidraw.md)
> 
> 再次感谢你关注这个问题！

修好了，去 release 下载最新的脚本试试吧，或者把仓库拉下来打包一份新的

**Comment by LeCheenaX** [comment]
> > > 竟然被你发现这个库了，发个测试文件，我今晚帮你看看，修复下
> > 
> > 
> > 感谢回复！抱歉回晚了。底下附件我刚刚测试了，全选方框之后，运行脚本就会复现问题。
> > ## 运行前：
> > ![image](https://private-user-images.githubusercontent.com/102142515/397994203-dee22132-f7bf-49be-8adf-9e8abfeb83c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTI1NTUsIm5iZiI6MTczNTA1MjI1NSwicGF0aCI6Ii8xMDIxNDI1MTUvMzk3OTk0MjAzLWRlZTIyMTMyLWY3YmYtNDliZS04YWRmLTllOGFiZmViODNjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNDU3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJhMDI1YTVkMWZiOTkzMjdkZDM1MjMwY2U2MDRlM2U2YWNjYmI5MjMyYzlkYTA5NWE0YjE0ODk2YWQwOGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NNRXwwlfKS2nibU597-DLPPZiiz4Cn105Yr1W5qq5ck)
> > 运行后：
> > ![image](https://private-user-images.githubusercontent.com/102142515/397994236-0f93d80f-d607-4c88-b41e-83aa25244032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTI1NTUsIm5iZiI6MTczNTA1MjI1NSwicGF0aCI6Ii8xMDIxNDI1MTUvMzk3OTk0MjM2LTBmOTNkODBmLWQ2MDctNGM4OC1iNDFlLTgzYWEyNTI0NDAzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNDU3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzNlYjVhYzAzOWNmMDRkMjMyZjlmZDA1MTFmNzFiMDc2NTMyNWE3MTA5NDBlZjcyZGJjYjAyMDAyOWQwMWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ONNXgk-TQS8KIgvfQQQPfF114Po5b8RMpJyiAEbCGGY)
> > 测试文件： [Drawing 2024-09-02 21.08.25.excalidraw.md](https://github.com/user-attachments/files/18222320/Drawing.2024-09-02.21.08.25.excalidraw.md)
> > 再次感谢你关注这个问题！
> 
> 修好了，去 release 下载最新的脚本试试吧，或者把仓库拉下来打包一份新的

确实修复了！感谢！大佬太牛啦： ）

**Comment by pandoralink** [comment]
有啥需求也可以提下，最近打算增加下功能～
